const content = {
  ar: {
    metaTitle: 'جمعية إنصاف سطيف | حماية الطفولة وتمكين الشباب',
    metaDescription: 'جمعية إنصاف سطيف تدافع عن حقوق الطفل، ترافق الشباب، وتدعم الإدماج الاجتماعي والتضامن المجتمعي منذ 2014.',
    brandName: 'جمعية إنصاف سطيف', brandTag: 'الدفاع عن حقوق الطفل وتمكين الشباب',
    navHome: 'الرئيسية', navAbout: 'من نحن', navPrograms: 'برامجنا', navMedia: 'المركز الإعلامي', navContact: 'اتصل بنا',
    heroEyebrow: 'جمعية مدنية جزائرية منذ جوان 2014', heroHeadline: 'عدالةٌ للطفولة، أملٌ للشباب، وتضامنٌ يخدم سطيف.', heroSubheadline: 'نعمل من أجل الدفاع عن حقوق الطفل، مرافقة الشباب، وتعزيز الإدماج الاجتماعي بالشراكة مع المؤسسات والجامعة والمجتمع المدني.', ctaPartner: 'كن شريكاً معنا', ctaReports: 'اكتشف برامجنا',
    impactA: 'حقوق الطفل', impactAText: 'حماية، ترافع، وتوعية قانونية', impactB: 'إدماج الشباب', impactBText: 'مرافقة نحو سوق العمل', impactC: 'تضامن مجتمعي', impactCText: 'دعم الفئات الهشة والاستجابة للأزمات',
    introLabel: 'لمحة', introTitle: 'منظمة قريبة من الأطفال والشباب ومؤسسات الولاية.', introText: 'جمعية إنصاف لولاية سطيف فاعل مدني يربط بين حماية الطفولة، مرافقة الشباب، والعمل التضامني. تعزز الجمعية حضور المجتمع المدني في النقاش العمومي والأنشطة الميدانية، وتبني تعاوناً مؤسساتياً مع شركاء محليين ووطنيين.',
    aboutLabel: 'من نحن', aboutTitle: 'تاريخنا ورسالتنا', historyText: 'تأسست جمعية إنصاف سطيف في جوان 2014 كجمعية مدنية معنية بالدفاع عن حقوق الطفل ومرافقة الشباب والفئات الهشة. تطورت الجمعية من مبادرات محلية إلى حضور مؤسساتي في قضايا الحماية، الإدماج، والتضامن.', missionTitle: 'الرسالة', missionText: 'الدفاع عن حقوق الطفل، ترسيخ ثقافة الحماية، ومرافقة الشباب والفئات الهشة نحو فرص أكثر عدلاً واندماجاً.', visionTitle: 'الرؤية', visionText: 'مجتمع محلي يضمن كرامة الطفل، يفتح مسارات للشباب، ويجعل التضامن مسؤولية مشتركة بين المؤسسات والمواطنين.',
    partnersLabel: 'شركاؤنا', partnersTitle: 'شبكة تعاون مؤسساتية ومدنية', partnerDjs: 'مديرية الشباب والرياضة - سطيف', partnerUni: 'جامعة محمد لمين دباغين سطيف 2', partnerWilaya: 'ولاية سطيف', partnerPrison: 'إدارة السجون وإعادة الإدماج', partnerYouth: 'ديوان مؤسسات الشباب - سطيف',
    programsLabel: 'برامجنا وأثرنا', programsTitle: 'أربعة محاور تخدم الطفل والشباب والمجتمع', pillar1Title: 'حقوق الطفل والحماية', pillar1Text: 'تنظم الجمعية أنشطة ترافع وتوعية حول حقوق الطفل، وتدعم ثقافة الحماية من خلال اللقاءات القانونية والتحسيسية والتنسيق مع الشركاء المعنيين بالطفولة. يركز هذا المحور على كرامة الطفل، الوقاية من المخاطر، وإبراز مسؤولية المجتمع في حماية كل طفل.', pillar2Title: 'إدماج الشباب والفئات الهشة', pillar2Text: 'تساهم إنصاف في مبادرات الإدماج الاجتماعي والمهني، خصوصاً ما يتصل بمرافقة الشباب والفئات الهشة نحو سوق العمل. ويشمل ذلك المشاركة في ملتقيات وطنية حول إعادة الإدماج، وبناء جسور بين المجتمع المدني والمؤسسات الاقتصادية والهيئات العمومية.', pillar3Title: 'التضامن المجتمعي', pillar3Text: 'تحافظ الجمعية على حضور تضامني قريب من المواطنين عبر دعم الأيتام، الاستجابة للأزمات، والمشاركة في فعاليات اجتماعية واسعة تخفف العبء عن العائلات. هذا المحور يترجم معنى الإنصاف إلى فعل ميداني قائم على الرحمة، الكرامة، وتعبئة المتطوعين.', pillar4Title: 'الشراكة والتواصل المدني', pillar4Text: 'تسعى الجمعية إلى شراكات فعالة مع المنتخبين، الجامعة، المصالح الولائية، والجمعيات النشطة. ويبرز هذا المحور في البيانات الإعلامية، اللقاءات التنسيقية، والحضور الرقمي الذي يفتح المجال للحوار، نشر الأخبار، وتشجيع التعاون بين الفاعلين المحليين.',
    mediaLabel: 'المركز الإعلامي', mediaTitle: 'آخر المحاور الإعلامية', media1Title: 'نشاطات فيسبوك', media1Text: 'مساحة لدمج منشورات الصفحة الرسمية وعرض أخبار الجمعية وبياناتها.', media2Title: 'فيديوهات وبرامج', media2Text: 'قسم مخصص للفيديوهات، بما فيها المواد التعريفية والبرامج الإعلامية مثل Sharek عند توفرها.', media3Title: 'بيانات وشراكات', media3Text: 'متابعة دعوات التعاون مع نواب الشعب، المؤسسات العمومية، والفاعلين المدنيين في سطيف.',
    brandLabel: 'هوية العلامة', brandTitle: 'ألوان وشخصية بصرية مستوحاة من الشعار', colorBlue: 'أزرق الثقة', colorNavy: 'أزرق مؤسساتي', colorYellow: 'أصفر الأمل', colorOrange: 'برتقالي التضامن', colorRed: 'أحمر المبادرة', brandStory: 'يجسد الشعار أشكالاً بشرية متعددة الألوان تلتقي في حركة دائرية حول مركز واحد، بما يعكس حماية الطفل، طاقة الشباب، وروح التضامن. توازن الألوان بين الثقة والنمو والدفء يجعل هوية إنصاف قريبة من الناس ومفتوحة على الشراكة.',
    contactLabel: 'اتصل بنا', contactTitle: 'لنتعاون من أجل طفولة آمنة وشباب مُمكّن', contactIntro: 'ترحب جمعية إنصاف سطيف بالجمعيات، المؤسسات، المتطوعين، والباحثين عن شراكات تخدم الطفل والشباب والفئات الهشة.', addressLabel: 'الموقع:', addressText: 'سطيف، الجزائر', phoneLabel: 'الهاتف:', placeholderPhone: 'يضاف رقم الهاتف الرسمي', emailLabel: 'البريد:', placeholderEmail: 'يضاف البريد الإلكتروني الرسمي', formName: 'الاسم الكامل', formOrg: 'الهيئة / الصفة', formEmail: 'البريد الإلكتروني', formMessage: 'رسالتك', formSubmit: 'إرسال الطلب', footerText: '© جمعية إنصاف سطيف — موقع تعريفي متعدد اللغات.', backTop: 'العودة إلى الأعلى'
  },
  fr: {
    metaTitle: 'Association Insaf Sétif | Droits de l’enfant',
    metaDescription: 'Insaf Sétif défend les droits de l’enfant, accompagne les jeunes et soutient la réinsertion sociale depuis 2014.',
    brandName: 'Association Insaf Sétif', brandTag: 'Droits de l’enfant et autonomisation des jeunes',
    navHome: 'Accueil', navAbout: 'Qui sommes-nous', navPrograms: 'Nos programmes', navMedia: 'Médiathèque', navContact: 'Contact',
    heroEyebrow: 'Association civile algérienne depuis juin 2014', heroHeadline: 'Justice pour l’enfance, espoir pour la jeunesse, solidarité pour Sétif.', heroSubheadline: 'Nous agissons pour défendre les droits de l’enfant, accompagner les jeunes et renforcer la réinsertion sociale en partenariat avec les institutions, l’université et la société civile.', ctaPartner: 'Devenir partenaire', ctaReports: 'Découvrir nos programmes',
    impactA: 'Droits de l’enfant', impactAText: 'Protection, plaidoyer et sensibilisation juridique', impactB: 'Insertion des jeunes', impactBText: 'Accompagnement vers le marché du travail', impactC: 'Solidarité communautaire', impactCText: 'Soutien aux publics vulnérables et réponse aux crises',
    introLabel: 'Aperçu', introTitle: 'Une organisation proche des enfants, des jeunes et des institutions locales.', introText: 'L’Association Insaf de la wilaya de Sétif relie protection de l’enfance, accompagnement des jeunes et action solidaire. Elle renforce la présence de la société civile dans le débat public et les activités de terrain, tout en développant une coopération institutionnelle avec des partenaires locaux et nationaux.',
    aboutLabel: 'Qui sommes-nous', aboutTitle: 'Notre histoire et notre mission', historyText: 'Fondée en juin 2014, l’Association Insaf Sétif est une association civile engagée dans la défense des droits de l’enfant, l’accompagnement des jeunes et le soutien aux publics vulnérables. Elle a évolué d’initiatives locales vers une présence institutionnelle sur les enjeux de protection, d’insertion et de solidarité.', missionTitle: 'Mission', missionText: 'Défendre les droits de l’enfant, promouvoir une culture de protection et accompagner les jeunes et les publics vulnérables vers des opportunités plus justes et inclusives.', visionTitle: 'Vision', visionText: 'Une communauté locale qui protège la dignité de l’enfant, ouvre des parcours aux jeunes et fait de la solidarité une responsabilité partagée entre institutions et citoyens.',
    partnersLabel: 'Partenaires', partnersTitle: 'Un réseau de coopération institutionnelle et civile', partnerDjs: 'Direction de la Jeunesse et des Sports - Sétif', partnerUni: 'Université Mohamed Lamine Debaghine Sétif 2', partnerWilaya: 'Wilaya de Sétif', partnerPrison: 'Administration pénitentiaire et réinsertion', partnerYouth: 'Office des établissements de jeunes - Sétif',
    programsLabel: 'Programmes & impact', programsTitle: 'Quatre piliers au service de l’enfant, des jeunes et de la communauté', pillar1Title: 'Droits et protection de l’enfant', pillar1Text: 'L’association mène des actions de plaidoyer et de sensibilisation autour des droits de l’enfant. Elle soutient une culture de protection à travers des rencontres juridiques, des activités de prévention et la coordination avec les partenaires concernés par l’enfance, afin de placer la dignité de chaque enfant au centre.', pillar2Title: 'Insertion des jeunes et publics vulnérables', pillar2Text: 'Insaf contribue aux initiatives d’insertion sociale et professionnelle, notamment l’accompagnement des jeunes et des publics vulnérables vers le marché du travail. Ce pilier comprend la participation à des rencontres nationales sur la réinsertion et la création de passerelles entre société civile, entreprises et institutions publiques.', pillar3Title: 'Solidarité communautaire', pillar3Text: 'L’association maintient une présence solidaire de proximité en soutenant les orphelins, en réagissant aux crises et en participant à des événements sociaux d’envergure qui allègent les familles. Ce pilier traduit l’équité en action concrète fondée sur la dignité, la compassion et la mobilisation des bénévoles.', pillar4Title: 'Partenariat et communication civile', pillar4Text: 'L’association recherche des partenariats efficaces avec les élus, l’université, les services de la wilaya et les associations actives. Ce pilier se manifeste par les communiqués, les rencontres de coordination et une présence numérique ouverte au dialogue, à l’information et à la coopération locale.',
    mediaLabel: 'Médiathèque', mediaTitle: 'Axes de communication récents', media1Title: 'Activités Facebook', media1Text: 'Espace destiné à intégrer les publications officielles et à présenter les actualités et communiqués de l’association.', media2Title: 'Vidéos et programmes', media2Text: 'Rubrique dédiée aux vidéos, supports de présentation et programmes médias tels que Sharek lorsqu’ils sont disponibles.', media3Title: 'Communiqués et partenariats', media3Text: 'Suivi des appels à la coopération avec les députés, institutions publiques et acteurs civils de Sétif.',
    brandLabel: 'Identité de marque', brandTitle: 'Couleurs et personnalité visuelle inspirées du logo', colorBlue: 'Bleu confiance', colorNavy: 'Bleu institutionnel', colorYellow: 'Jaune espoir', colorOrange: 'Orange solidarité', colorRed: 'Rouge initiative', brandStory: 'Le logo présente des figures humaines multicolores réunies dans un mouvement circulaire autour d’un centre commun. Il évoque la protection de l’enfant, l’énergie de la jeunesse et l’esprit de solidarité. L’équilibre entre confiance, croissance et chaleur rend l’identité d’Insaf proche des citoyens et ouverte au partenariat.',
    contactLabel: 'Contact', contactTitle: 'Coopérons pour une enfance protégée et une jeunesse accompagnée', contactIntro: 'L’Association Insaf Sétif accueille les associations, institutions, bénévoles et partenaires souhaitant agir pour l’enfant, les jeunes et les publics vulnérables.', addressLabel: 'Adresse :', addressText: 'Sétif, Algérie', phoneLabel: 'Téléphone :', placeholderPhone: 'Numéro officiel à ajouter', emailLabel: 'E-mail :', placeholderEmail: 'Adresse officielle à ajouter', formName: 'Nom complet', formOrg: 'Organisation / qualité', formEmail: 'E-mail', formMessage: 'Votre message', formSubmit: 'Envoyer la demande', footerText: '© Association Insaf Sétif — site vitrine trilingue.', backTop: 'Retour en haut'
  },
  en: {
    metaTitle: 'Association Insaf Sétif | Child Rights',
    metaDescription: 'Insaf Sétif promotes child rights, supports youth accompaniment, and strengthens social reintegration and solidarity since 2014.',
    brandName: 'Association Insaf Sétif', brandTag: 'Child rights and youth empowerment',
    navHome: 'Home', navAbout: 'About Us', navPrograms: 'Our Programs', navMedia: 'Media Center', navContact: 'Contact',
    heroEyebrow: 'Algerian civil society association since June 2014', heroHeadline: 'Justice for children, hope for youth, solidarity for Sétif.', heroSubheadline: 'We work to defend children’s rights, accompany young people, and strengthen social reintegration through partnerships with institutions, universities, and civil society.', ctaPartner: 'Partner With Us', ctaReports: 'Explore Programs',
    impactA: 'Child Rights', impactAText: 'Protection, advocacy, and legal awareness', impactB: 'Youth Reintegration', impactBText: 'Accompaniment toward the labor market', impactC: 'Community Solidarity', impactCText: 'Support for vulnerable groups and crisis response',
    introLabel: 'Overview', introTitle: 'An organization close to children, youth, and local institutions.', introText: 'Association Insaf in Sétif connects child protection, youth accompaniment, and solidarity action. The association strengthens civil society participation in public dialogue and field activities while building institutional cooperation with local and national partners.',
    aboutLabel: 'About Us', aboutTitle: 'Our history and mission', historyText: 'Established in June 2014, Association Insaf Sétif is a civil society organization dedicated to defending children’s rights, accompanying young people, and supporting vulnerable groups. It has grown from local initiatives into institutional engagement around protection, reintegration, and solidarity.', missionTitle: 'Mission', missionText: 'To defend children’s rights, promote a culture of protection, and accompany youth and vulnerable groups toward fairer and more inclusive opportunities.', visionTitle: 'Vision', visionText: 'A local community that protects every child’s dignity, opens pathways for young people, and makes solidarity a shared responsibility between institutions and citizens.',
    partnersLabel: 'Partners', partnersTitle: 'A network of institutional and civic cooperation', partnerDjs: 'Youth and Sports Directorate - Sétif', partnerUni: 'Mohamed Lamine Debaghine Sétif 2 University', partnerWilaya: 'Wilaya of Sétif', partnerPrison: 'Prison Administration and Reintegration', partnerYouth: 'Youth Establishments Office - Sétif',
    programsLabel: 'Programs & Impact', programsTitle: 'Four pillars serving children, youth, and community', pillar1Title: 'Child Rights & Protection', pillar1Text: 'The association leads advocacy and awareness activities around children’s rights. It supports a culture of protection through legal seminars, prevention-oriented outreach, and coordination with child-focused partners, keeping the dignity of every child and the shared responsibility of society at the heart of its work.', pillar2Title: 'Youth and Vulnerable Groups Reintegration', pillar2Text: 'Insaf contributes to social and professional reintegration initiatives, especially by accompanying youth and vulnerable groups toward the labor market. This pillar includes participation in national reintegration forums and building bridges between civil society, economic actors, and public institutions.', pillar3Title: 'Community Solidarity', pillar3Text: 'The association maintains a close solidarity presence by supporting orphans, responding to crises, and participating in large social events that ease the burden on families. This pillar turns equity into field action grounded in dignity, compassion, and volunteer mobilization.', pillar4Title: 'Partnership & Civic Communication', pillar4Text: 'The association seeks effective partnerships with elected representatives, universities, wilaya services, and active associations. This pillar appears through media statements, coordination meetings, and a digital presence that opens space for dialogue, news sharing, and local cooperation.',
    mediaLabel: 'Media Center', mediaTitle: 'Recent communication areas', media1Title: 'Facebook Activity', media1Text: 'A space to integrate official page posts and display the association’s news and statements.', media2Title: 'Videos and Programs', media2Text: 'A section for videos, presentation material, and media programs such as Sharek when available.', media3Title: 'Statements and Partnerships', media3Text: 'Follow-up on calls for cooperation with parliament representatives, public institutions, and civic actors in Sétif.',
    brandLabel: 'Brand Identity', brandTitle: 'Colors and visual personality inspired by the logo', colorBlue: 'Trust Blue', colorNavy: 'Institutional Blue', colorYellow: 'Hope Yellow', colorOrange: 'Solidarity Orange', colorRed: 'Initiative Red', brandStory: 'The logo shows colorful human figures moving in a circle around a shared center. It suggests child protection, youth energy, and the spirit of solidarity. The balance of trust, growth, and warmth makes Insaf’s identity approachable for citizens and open to partnership.',
    contactLabel: 'Contact', contactTitle: 'Let’s cooperate for protected children and empowered youth', contactIntro: 'Association Insaf Sétif welcomes associations, institutions, volunteers, and partners who want to serve children, young people, and vulnerable groups.', addressLabel: 'Location:', addressText: 'Sétif, Algeria', phoneLabel: 'Phone:', placeholderPhone: 'Official phone number to be added', emailLabel: 'Email:', placeholderEmail: 'Official email to be added', formName: 'Full name', formOrg: 'Organization / role', formEmail: 'Email', formMessage: 'Your message', formSubmit: 'Send request', footerText: '© Association Insaf Sétif — trilingual informational website.', backTop: 'Back to top'
  }
};

function applyLanguage(lang) {
  const pack = content[lang] || content.ar;
  document.documentElement.lang = lang;
  document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  document.title = pack.metaTitle;
  document.querySelector('meta[name="description"]').setAttribute('content', pack.metaDescription);
  document.querySelectorAll('[data-i18n]').forEach((node) => {
    const key = node.dataset.i18n;
    if (pack[key]) node.textContent = pack[key];
  });
  document.querySelectorAll('[data-lang]').forEach((button) => button.classList.toggle('active', button.dataset.lang === lang));
  localStorage.setItem('insaf-lang', lang);
}

document.querySelectorAll('[data-lang]').forEach((button) => {
  button.addEventListener('click', () => applyLanguage(button.dataset.lang));
});

const navToggle = document.querySelector('.nav-toggle');
const nav = document.querySelector('.main-nav');
navToggle?.addEventListener('click', () => {
  const isOpen = nav.classList.toggle('open');
  navToggle.setAttribute('aria-expanded', String(isOpen));
});
nav?.querySelectorAll('a').forEach((link) => link.addEventListener('click', () => nav.classList.remove('open')));

applyLanguage(localStorage.getItem('insaf-lang') || 'ar');
