// Children's rights hub content (ar / fr / en).
// Every legal date and helpline below was checked against official or press sources on
// 2026-09-19. Every "what Insaf does" line comes from the association's own published
// activities. Keep it that way: add a claim only when there is a post or document behind it.

export const RIGHTS_SOURCES = [
  { id: 'unicefKids', org: 'UNICEF', url: 'https://www.unicef.org/child-rights-convention/convention-text-childrens-version' },
  { id: 'crcText', org: 'OHCHR', url: 'https://www.ohchr.org/en/instruments-mechanisms/instruments/convention-rights-child' },
  { id: 'gc26', org: 'OHCHR', url: 'https://www.ohchr.org/en/documents/general-comments-and-recommendations/crccgc26-general-comment-no-26-2023-childrens-rights' },
  { id: 'acrwc', org: 'African Union', url: 'https://au.int/en/treaties/african-charter-rights-and-welfare-child' },
  { id: 'law1512', org: 'UNICEF Algérie', url: 'https://www.unicef.org/algeria/documents/la-loi-n-15-12-relative-%C3%A0-la-protection-de-lenfant' },
  { id: 'onppe', org: 'ONPPE', url: 'https://network.onppe.dz/' },
  { id: 'nada', org: 'Réseau NADA', url: 'https://www.reseaunada.com/' },
];

export const HELPLINES = [
  { id: 'onppe', number: '1111', tel: '1111' },
  { id: 'nada', number: '3033', tel: '3033' },
];

export const EMERGENCY_NUMBERS = [
  { id: 'civil', number: '14', tel: '14' },
  { id: 'police', number: '1548', tel: '1548' },
];

// Order matters: it is the order of the explorer grid.
export const RIGHT_IDS = ['education', 'health', 'protection', 'living', 'family', 'play', 'voice', 'environment'];

export const childRights = {
  ar: {
    badge: 'حقوق الطفل',
    title: 'لكل طفل حقوق… ولكل حقّ من يحميه.',
    lead: 'اتفاقية الأمم المتحدة لحقوق الطفل تضمن لكل من هو دون الثامنة عشرة حقوقًا لا تسقط. هنا نشرحها ببساطة، ونبيّن ما تقوم به جمعية إنصاف لتصبح واقعًا في سطيف.',
    teaserCta: 'اكتشف حقوق الطفل',
    principlesTitle: 'أربعة مبادئ تقوم عليها الاتفاقية',
    principlesLead: 'كل حق في الاتفاقية يُقرأ على ضوء هذه المبادئ الأربعة.',
    articleLabel: 'المادة',
    principles: [
      { id: 'nondiscrimination', article: '2', title: 'عدم التمييز', text: 'الحقوق نفسها لكل طفل، أيًّا كان أصله أو جنسه أو إعاقته أو وضع أسرته.' },
      { id: 'bestInterests', article: '3', title: 'مصلحة الطفل الفضلى', text: 'في كل قرار يمسّ الطفل، تأتي مصلحته أولًا.' },
      { id: 'life', article: '6', title: 'الحياة والبقاء والنماء', text: 'لكل طفل الحق في الحياة وفي أن ينمو بصحة وأمان إلى أقصى ما يستطيع.' },
      { id: 'voice', article: '12', title: 'احترام رأي الطفل', text: 'للطفل أن يعبّر عن رأيه في ما يخصّه، وأن يؤخذ رأيه بجدّية.' },
    ],
    rightsTitle: 'مستكشف الحقوق',
    rightsLead: 'اختر حقًّا لتقرأه بلغة الطفل، وترى ما تفعله إنصاف من أجله.',
    childVoice: 'بلغة الطفل',
    insafDoes: 'ما تفعله إنصاف',
    rights: {
      education:   { articles: '28 · 29', title: 'التعليم', child: 'من حقي أن أتعلّم في مدرسة، وأن يساعدني التعليم على أن أكتشف مواهبي.', insaf: 'حقائب مدرسية للأطفال الأيتام وأبناء الأسر المعوزة مع كل دخول مدرسي، ومسابقة التهجئة الإنجليزية (Spelling Bee) التي ننظّمها في سطيف مع شركائنا.' },
      health:      { articles: '24', title: 'الصحة', child: 'من حقي أن أُعالَج حين أمرض، وأن أشرب ماءً نظيفًا وآكل طعامًا صحيًّا.', insaf: 'نادي «صحتي فرست» ينظّم ورشات حول صحة الطفل، وصندوق الرعاية الصحية يموّل الفحوص والأدوية الأساسية.' },
      protection:  { articles: '19', title: 'الحماية من العنف', child: 'لا يحق لأحد أن يؤذيني أو يهملني. وإن حدث ذلك، أستطيع طلب المساعدة.', insaf: 'ورشات توعوية للأطفال وللأولياء، وتوجيه الأسر نحو الرقمين الأخضرين 1111 و3033.' },
      living:      { articles: '27', title: 'مستوى معيشي لائق', child: 'من حقي أن أجد ما يكفيني من غذاء وملبس ومسكن دافئ.', insaf: 'ملابس الشتاء الدافئة وقفّة التضامن للأسر المحتاجة في ولاية سطيف.' },
      family:      { articles: '20', title: 'الرعاية الأسرية', child: 'إذا لم أستطع العيش مع أسرتي، فمن حقي أن أجد رعاية خاصة وبيتًا آمنًا.', insaf: 'مرافقة الأطفال الأيتام والأسر التي تكفلهم، ضمن محور التضامن المجتمعي.' },
      play:        { articles: '31', title: 'اللعب والراحة', child: 'من حقي أن ألعب وأرتاح وأشارك في الأنشطة الثقافية والفنية.', insaf: 'خرجات وألعاب وورشات رسم، مثل خرجة اليوم العالمي للطفل إلى جبل مقرس (عين عباسة).' },
      voice:       { articles: '12 · 13', title: 'التعبير والمشاركة', child: 'من حقي أن أقول رأيي، وأن يُستمع إليّ في ما يخصّني.', insaf: 'نادي سفراء حقوق الطفل: أطفال يتعلّمون حقوقهم ويتحدّثون باسم أقرانهم.' },
      environment: { articles: '24 · 29 · التعليق العام 26', title: 'بيئة سليمة', child: 'من حقي أن أعيش في بيئة نظيفة وصحية، وأن أتعلّم كيف أحميها.', insaf: 'حملات تنظيف خلال خرجاتنا، والمشاركة في الحملة الوطنية لاسترجاع الكراريس المستعملة وإعادة تدويرها.' },
    },
    helpTitle: 'هل هناك طفل في خطر؟',
    helpLead: 'لا تنتظر. الاتصال مجاني وسرّي، ويمكن لأي شخص أن يبلّغ.',
    helplines: {
      onppe: { name: 'الهيئة الوطنية لحماية وترقية الطفولة', detail: 'رقم أخضر مجاني، يعمل 24/24 وطوال أيام الأسبوع، مع أخصائيين نفسانيين واجتماعيين وقانونيين. ويمكن التبليغ أيضًا عبر تطبيق «ألو طفولة».' },
      nada:  { name: 'الشبكة الجزائرية للدفاع عن حقوق الطفل «ندى»', detail: 'خلية إصغاء مجانية منذ 2008، من الهاتف الثابت ومن شبكات الهاتف النقال الثلاث.' },
    },
    callLabel: 'اتصل بالرقم',
    emergencyLabel: 'خطر فوري؟',
    emergency: { civil: 'الحماية المدنية', police: 'الشرطة' },
    lawTitle: 'الجزائر تحمي أطفالها بالقانون',
    lawLead: 'محطات أساسية في الإطار القانوني لحماية الطفولة في الجزائر.',
    timeline: [
      { date: '20 نوفمبر 1989', title: 'اعتماد الاتفاقية', text: 'الجمعية العامة للأمم المتحدة تعتمد اتفاقية حقوق الطفل.' },
      { date: '26 جانفي 1990', title: 'توقيع الجزائر', text: 'الجزائر توقّع على اتفاقية حقوق الطفل.' },
      { date: '16 أفريل 1993', title: 'مصادقة الجزائر', text: 'الجزائر تصادق على الاتفاقية فتصبح ملزمة بها.' },
      { date: '8 جويلية 2003', title: 'الميثاق الإفريقي', text: 'المرسوم الرئاسي رقم 03-242 يصادق على الميثاق الإفريقي لحقوق الطفل ورفاهيته.' },
      { date: '15 جويلية 2015', title: 'قانون حماية الطفل 15-12', text: 'كل من لم يبلغ 18 سنة طفل. حماية اجتماعية وقضائية للطفل في خطر، وإنشاء الهيئة الوطنية لحماية وترقية الطفولة (المادة 11) التي يرفع مفوّضها الوطني تقريرًا سنويًّا عن وضعية حقوق الطفل.' },
    ],
    datesTitle: 'مواعيد نحتفي بها',
    dates: [
      { day: '1', month: 'جوان', title: 'اليوم العالمي للطفولة', text: 'نحييه كل سنة مع أطفال سطيف بخرجات وورشات.' },
      { day: '16', month: 'جوان', title: 'يوم الطفل الإفريقي', text: 'تذكير بالميثاق الإفريقي الذي صادقت عليه الجزائر.' },
      { day: '20', month: 'نوفمبر', title: 'اليوم العالمي للطفل', text: 'ذكرى اعتماد اتفاقية حقوق الطفل سنة 1989.' },
    ],
    ambassadorsBadge: 'من داخل إنصاف',
    ambassadorsTitle: 'نادي سفراء حقوق الطفل',
    ambassadorsText: 'في نادي سفراء حقوق الطفل يتعلّم الأطفال حقوقهم ويشاركون في ورشات الرسم والصحة والتوعية. يعمل النادي مع نادي «صحتي فرست» في إطار مشروع «فرصتي، كلنا شركاء فاعلون» للشبكة الجزائرية للدفاع عن حقوق الطفل «ندى».',
    ctaJoin: 'سجّل طفلك في النادي',
    ctaSupport: 'ادعم برامج الأطفال',
    promiseTitle: 'كيف نحمي الأطفال في ما ننشره',
    promises: [
      'لا ننشر أبدًا الاسم الكامل لطفل أو عنوانه أو مدرسته.',
      'القصص على هذا الموقع مركّبة من عدة حالات، والأسماء مغيّرة.',
      'الصور من أنشطة عمومية. وإذا كنت وليًّا وتريد حذف صورة، راسلنا.',
      'إن رأيت طفلًا في خطر، اتصل بالرقم 1111 أولًا، ثم أخبرنا.',
    ],
    promiseCta: 'طلب حذف صورة',
    sourcesTitle: 'المصادر',
    sourcesNote: 'نذكر هذه الهيئات كمراجع فقط، ولا يعني ذلك وجود شراكة معها.',
    sources: {
      unicefKids: 'اتفاقية حقوق الطفل بلغة مبسّطة للأطفال',
      crcText: 'النص الكامل لاتفاقية حقوق الطفل',
      gc26: 'التعليق العام رقم 26 (2023): حقوق الطفل والبيئة',
      acrwc: 'الميثاق الإفريقي لحقوق الطفل ورفاهيته',
      law1512: 'القانون 15-12 المتعلق بحماية الطفل',
      onppe: 'الهيئة الوطنية لحماية وترقية الطفولة',
      nada: 'الشبكة الجزائرية للدفاع عن حقوق الطفل «ندى»',
    },
  },

  fr: {
    badge: 'Droits de l’enfant',
    title: 'Chaque enfant a des droits… et chaque droit mérite un protecteur.',
    lead: 'La Convention des Nations unies relative aux droits de l’enfant garantit à toute personne de moins de 18 ans des droits inaliénables. Nous les expliquons simplement, et nous montrons ce que fait Insaf pour qu’ils deviennent réalité à Sétif.',
    teaserCta: 'Découvrir les droits de l’enfant',
    principlesTitle: 'Les quatre principes de la Convention',
    principlesLead: 'Chaque droit de la Convention se lit à la lumière de ces quatre principes.',
    articleLabel: 'Article',
    principles: [
      { id: 'nondiscrimination', article: '2', title: 'Non-discrimination', text: 'Les mêmes droits pour chaque enfant, quels que soient son origine, son sexe, son handicap ou la situation de sa famille.' },
      { id: 'bestInterests', article: '3', title: 'Intérêt supérieur de l’enfant', text: 'Dans toute décision qui le concerne, l’intérêt de l’enfant passe en premier.' },
      { id: 'life', article: '6', title: 'Vie, survie et développement', text: 'Chaque enfant a droit à la vie et à grandir en bonne santé et en sécurité, au mieux de ses capacités.' },
      { id: 'voice', article: '12', title: 'Respect de l’opinion de l’enfant', text: 'L’enfant peut exprimer son avis sur ce qui le concerne, et cet avis doit être pris au sérieux.' },
    ],
    rightsTitle: 'Explorer les droits',
    rightsLead: 'Choisissez un droit pour le lire avec les mots d’un enfant et voir ce qu’Insaf fait pour lui.',
    childVoice: 'Avec les mots d’un enfant',
    insafDoes: 'Ce que fait Insaf',
    rights: {
      education:   { articles: '28 · 29', title: 'Éducation', child: 'J’ai le droit d’aller à l’école et d’apprendre à développer mes talents.', insaf: 'Des cartables complets pour les orphelins et les enfants de familles modestes à chaque rentrée, et le concours national d’épellation anglaise (Spelling Bee) organisé à Sétif avec nos partenaires.' },
      health:      { articles: '24', title: 'Santé', child: 'J’ai le droit d’être soigné quand je suis malade, de boire de l’eau propre et de manger sainement.', insaf: 'Le club « Sahti First » anime des ateliers sur la santé de l’enfant ; le fonds santé finance consultations et médicaments essentiels.' },
      protection:  { articles: '19', title: 'Protection contre la violence', child: 'Personne n’a le droit de me faire du mal ou de me négliger. Si cela arrive, je peux demander de l’aide.', insaf: 'Des ateliers de sensibilisation pour les enfants et les parents, et l’orientation des familles vers les numéros verts 1111 et 3033.' },
      living:      { articles: '27', title: 'Niveau de vie suffisant', child: 'J’ai le droit d’avoir assez à manger, des vêtements et un logement chaud.', insaf: 'Vêtements d’hiver chauds et couffins de solidarité pour les familles dans le besoin de la wilaya de Sétif.' },
      family:      { articles: '20', title: 'Protection de remplacement', child: 'Si je ne peux pas vivre avec ma famille, j’ai droit à une protection spéciale et à un foyer sûr.', insaf: 'L’accompagnement des enfants orphelins et des familles qui les prennent en charge, dans notre pilier de solidarité communautaire.' },
      play:        { articles: '31', title: 'Jeu et loisirs', child: 'J’ai le droit de jouer, de me reposer et de participer à des activités culturelles et artistiques.', insaf: 'Sorties, jeux et ateliers de dessin, comme la sortie de la Journée de l’enfance au mont Megress (Aïn Abessa).' },
      voice:       { articles: '12 · 13', title: 'Expression et participation', child: 'J’ai le droit de donner mon avis et d’être écouté sur ce qui me concerne.', insaf: 'Le club des Ambassadeurs des droits de l’enfant : des enfants apprennent leurs droits et parlent au nom de leurs pairs.' },
      environment: { articles: '24 · 29 · Observation générale 26', title: 'Environnement sain', child: 'J’ai le droit de vivre dans un environnement propre et sain, et d’apprendre à le protéger.', insaf: 'Des opérations de nettoyage pendant nos sorties, et notre participation à la campagne nationale de collecte et de recyclage des cahiers usagés.' },
    },
    helpTitle: 'Un enfant en danger ?',
    helpLead: 'N’attendez pas. L’appel est gratuit et confidentiel, et tout le monde peut signaler.',
    helplines: {
      onppe: { name: 'Organe national de la protection et de la promotion de l’enfance (ONPPE)', detail: 'Numéro vert gratuit, 24 h/24 et 7 j/7, avec des psychologues, des sociologues et des juristes. Signalement possible aussi via l’application « Allô Tofola ».' },
      nada:  { name: 'Réseau algérien pour la défense des droits de l’enfant (NADA)', detail: 'Cellule d’écoute gratuite depuis 2008, depuis le fixe et les trois réseaux mobiles.' },
    },
    callLabel: 'Appeler le',
    emergencyLabel: 'Danger immédiat ?',
    emergency: { civil: 'Protection civile', police: 'Police' },
    lawTitle: 'L’Algérie protège ses enfants par la loi',
    lawLead: 'Les étapes clés du cadre juridique de la protection de l’enfance en Algérie.',
    timeline: [
      { date: '20 novembre 1989', title: 'Adoption de la Convention', text: 'L’Assemblée générale des Nations unies adopte la Convention relative aux droits de l’enfant.' },
      { date: '26 janvier 1990', title: 'Signature de l’Algérie', text: 'L’Algérie signe la Convention relative aux droits de l’enfant.' },
      { date: '16 avril 1993', title: 'Ratification', text: 'L’Algérie ratifie la Convention, qui devient contraignante pour elle.' },
      { date: '8 juillet 2003', title: 'Charte africaine', text: 'Le décret présidentiel n° 03-242 ratifie la Charte africaine des droits et du bien-être de l’enfant.' },
      { date: '15 juillet 2015', title: 'Loi 15-12 relative à la protection de l’enfant', text: 'Est enfant toute personne de moins de 18 ans. Protection sociale et judiciaire de l’enfant en danger, et création de l’ONPPE (article 11), dont le Délégué national publie chaque année un rapport sur la situation des droits de l’enfant.' },
    ],
    datesTitle: 'Les dates que nous célébrons',
    dates: [
      { day: '1', month: 'juin', title: 'Journée internationale de l’enfance', text: 'Nous la fêtons chaque année avec les enfants de Sétif, par des sorties et des ateliers.' },
      { day: '16', month: 'juin', title: 'Journée de l’enfant africain', text: 'Un rappel de la Charte africaine ratifiée par l’Algérie.' },
      { day: '20', month: 'nov.', title: 'Journée mondiale de l’enfance', text: 'L’anniversaire de l’adoption de la Convention en 1989.' },
    ],
    ambassadorsBadge: 'Au cœur d’Insaf',
    ambassadorsTitle: 'Le club des Ambassadeurs des droits de l’enfant',
    ambassadorsText: 'Au club des Ambassadeurs des droits de l’enfant, les enfants apprennent leurs droits et participent à des ateliers de dessin, de santé et de sensibilisation. Le club travaille avec le club « Sahti First » dans le cadre du projet « Forsati, tous partenaires actifs » du Réseau NADA.',
    ctaJoin: 'Inscrire mon enfant au club',
    ctaSupport: 'Soutenir les programmes enfance',
    promiseTitle: 'Comment nous protégeons les enfants dans ce que nous publions',
    promises: [
      'Nous ne publions jamais le nom complet, l’adresse ou l’école d’un enfant.',
      'Les récits de ce site sont des compositions de plusieurs situations ; les prénoms sont changés.',
      'Les photos proviennent d’activités publiques. Parent ou tuteur, vous voulez qu’une photo soit retirée ? Écrivez-nous.',
      'Si vous voyez un enfant en danger, appelez d’abord le 1111, puis prévenez-nous.',
    ],
    promiseCta: 'Demander le retrait d’une photo',
    sourcesTitle: 'Sources',
    sourcesNote: 'Ces organismes sont cités comme références ; cela n’implique aucun partenariat.',
    sources: {
      unicefKids: 'La Convention relative aux droits de l’enfant, version pour les enfants',
      crcText: 'Texte intégral de la Convention relative aux droits de l’enfant',
      gc26: 'Observation générale n° 26 (2023) : droits de l’enfant et environnement',
      acrwc: 'Charte africaine des droits et du bien-être de l’enfant',
      law1512: 'Loi n° 15-12 relative à la protection de l’enfant',
      onppe: 'Organe national de la protection et de la promotion de l’enfance',
      nada: 'Réseau algérien pour la défense des droits de l’enfant (NADA)',
    },
  },

  en: {
    badge: 'Children’s rights',
    title: 'Every child has rights… and every right needs someone to protect it.',
    lead: 'The UN Convention on the Rights of the Child guarantees every person under 18 rights that can never be taken away. Here we explain them simply, and show what Insaf does to make them real in Sétif.',
    teaserCta: 'Explore children’s rights',
    principlesTitle: 'The four principles behind the Convention',
    principlesLead: 'Every right in the Convention is read in the light of these four principles.',
    articleLabel: 'Article',
    principles: [
      { id: 'nondiscrimination', article: '2', title: 'Non-discrimination', text: 'The same rights for every child, whatever their origin, sex, disability or family situation.' },
      { id: 'bestInterests', article: '3', title: 'Best interests of the child', text: 'In every decision that affects a child, the child’s interests come first.' },
      { id: 'life', article: '6', title: 'Life, survival and development', text: 'Every child has the right to life and to grow up healthy and safe, as fully as they can.' },
      { id: 'voice', article: '12', title: 'Respect for the child’s views', text: 'Children can say what they think about matters that affect them, and be taken seriously.' },
    ],
    rightsTitle: 'Rights explorer',
    rightsLead: 'Pick a right to read it in a child’s words and see what Insaf does for it.',
    childVoice: 'In a child’s words',
    insafDoes: 'What Insaf does',
    rights: {
      education:   { articles: '28 · 29', title: 'Education', child: 'I have the right to go to school and to learn in a way that helps my talents grow.', insaf: 'School kits for orphans and children from low-income families every back-to-school season, and the national English Spelling Bee we host in Sétif with our partners.' },
      health:      { articles: '24', title: 'Health', child: 'I have the right to care when I am sick, to clean water and to healthy food.', insaf: 'Our “Sahti First” club runs child-health workshops; the healthcare fund pays for check-ups and essential medicines.' },
      protection:  { articles: '19', title: 'Protection from violence', child: 'No one is allowed to hurt me or neglect me. If it happens, I can ask for help.', insaf: 'Awareness workshops for children and parents, and guidance for families towards the free 1111 and 3033 helplines.' },
      living:      { articles: '27', title: 'A decent standard of living', child: 'I have the right to enough food, clothes and a warm home.', insaf: 'Warm winter clothing and solidarity food baskets for families in need across Sétif province.' },
      family:      { articles: '20', title: 'Care without a family', child: 'If I cannot live with my family, I have the right to special care and a safe home.', insaf: 'Support for orphaned children and the families who raise them, through our community-solidarity work.' },
      play:        { articles: '31', title: 'Play and rest', child: 'I have the right to play, to rest and to take part in culture and art.', insaf: 'Outings, games and drawing workshops, like our Children’s Day trip to Mount Megress (Aïn Abessa).' },
      voice:       { articles: '12 · 13', title: 'Expression and participation', child: 'I have the right to give my opinion and to be listened to about things that affect me.', insaf: 'The Children’s Rights Ambassadors Club: children learn their rights and speak up for their peers.' },
      environment: { articles: '24 · 29 · General Comment 26', title: 'A healthy environment', child: 'I have the right to live in a clean, healthy environment and to learn how to protect it.', insaf: 'Clean-ups during our outings, and taking part in the national campaign to collect and recycle used school notebooks.' },
    },
    helpTitle: 'Is a child in danger?',
    helpLead: 'Don’t wait. Calls are free and confidential, and anyone can report.',
    helplines: {
      onppe: { name: 'National Body for the Protection and Promotion of Childhood (ONPPE)', detail: 'Free line, 24/7, answered by psychologists, sociologists and lawyers. You can also report through the “Allô Tofola” app.' },
      nada:  { name: 'Algerian Network for the Defence of Children’s Rights (NADA)', detail: 'A free listening line since 2008, from landlines and all three mobile networks.' },
    },
    callLabel: 'Call',
    emergencyLabel: 'Immediate danger?',
    emergency: { civil: 'Civil Protection', police: 'Police' },
    lawTitle: 'Algeria protects its children by law',
    lawLead: 'Key milestones in Algeria’s legal framework for child protection.',
    timeline: [
      { date: '20 November 1989', title: 'The Convention is adopted', text: 'The UN General Assembly adopts the Convention on the Rights of the Child.' },
      { date: '26 January 1990', title: 'Algeria signs', text: 'Algeria signs the Convention on the Rights of the Child.' },
      { date: '16 April 1993', title: 'Algeria ratifies', text: 'Algeria ratifies the Convention, making it binding.' },
      { date: '8 July 2003', title: 'The African Charter', text: 'Presidential Decree 03-242 ratifies the African Charter on the Rights and Welfare of the Child.' },
      { date: '15 July 2015', title: 'Child Protection Law 15-12', text: 'Anyone under 18 is a child. Social and judicial protection for children in danger, and the creation of ONPPE (Article 11), whose National Delegate reports every year on the state of children’s rights.' },
    ],
    datesTitle: 'Dates we celebrate',
    dates: [
      { day: '1', month: 'June', title: 'International Children’s Day', text: 'We mark it every year with Sétif’s children through outings and workshops.' },
      { day: '16', month: 'June', title: 'Day of the African Child', text: 'A reminder of the African Charter that Algeria has ratified.' },
      { day: '20', month: 'Nov', title: 'World Children’s Day', text: 'The anniversary of the Convention’s adoption in 1989.' },
    ],
    ambassadorsBadge: 'Inside Insaf',
    ambassadorsTitle: 'The Children’s Rights Ambassadors Club',
    ambassadorsText: 'In the Children’s Rights Ambassadors Club, children learn their rights and take part in drawing, health and awareness workshops. The club works alongside our “Sahti First” club within the “Forsati — all active partners” project of the NADA network.',
    ctaJoin: 'Sign my child up for the club',
    ctaSupport: 'Support children’s programmes',
    promiseTitle: 'How we protect children in what we publish',
    promises: [
      'We never publish a child’s full name, address or school.',
      'Stories on this site combine several situations; names are changed.',
      'Photos come from public activities. Parent or guardian and want a photo removed? Write to us.',
      'If you see a child in danger, call 1111 first, then tell us.',
    ],
    promiseCta: 'Ask us to remove a photo',
    sourcesTitle: 'Sources',
    sourcesNote: 'These bodies are cited as references only; this does not imply a partnership.',
    sources: {
      unicefKids: 'The Convention on the Rights of the Child, children’s version',
      crcText: 'Full text of the Convention on the Rights of the Child',
      gc26: 'General Comment No. 26 (2023): children’s rights and the environment',
      acrwc: 'African Charter on the Rights and Welfare of the Child',
      law1512: 'Law 15-12 on the protection of the child',
      onppe: 'National Body for the Protection and Promotion of Childhood',
      nada: 'Algerian Network for the Defence of Children’s Rights (NADA)',
    },
  },
};
