// Trust & transparency page copy (ar / fr / en).
// Statements here describe what the website and the donation flow actually do. Anything
// that depends on the association's own documents lives in config/trust.js as pending.

export const trust = {
  ar: {
    promisesTitle: 'أربعة التزامات أمام كل متبرّع',
    promises: [
      { id: 'choose', title: 'أنت من يختار وجهة تبرّعك', text: 'كل تبرّع يحمل وجهته: الدخول المدرسي، الصحة، الشتاء، صندوق الحرائق، رمضان، أو حيث الحاجة أكبر.' },
      { id: 'prove', title: 'لا ننشر إلا ما نستطيع إثباته', text: 'أي رقم لم يتم التحقق منه بعد يظهر على الموقع بعبارة «توضيحي».' },
      { id: 'children', title: 'الأطفال أولًا', text: 'لا اسم كامل، ولا عنوان، ولا مدرسة لأي طفل في ما ننشره.' },
      { id: 'candid', title: 'نعترف حين يتعثّر شيء', text: 'إن تأخّر مشروع أو تغيّر رقم، نكتب ذلك هنا مع تاريخه.' },
    ],
    fundsTitle: 'أين يذهب دينارك؟',
    fundsLead: 'اختر الصندوق الذي تريد دعمه، أو اترك القرار لنا ليذهب حيث الحاجة أكبر.',
    funds: {
      general:  { title: 'حيث الحاجة أكبر', text: 'يُوجَّه إلى البرنامج الأكثر استعجالًا في وقته.' },
      school:   { title: 'الحقائب المدرسية', text: 'كراريس وأدوات ومحفظة ومئزر لطفل يتيم أو من أسرة معوزة. 5 000 دج للحقيبة الكاملة.' },
      health:   { title: 'الرعاية الصحية للأطفال', text: 'فحوص طبية وأدوية أساسية ومتابعة طوال السنة. 8 000 دج لطفل واحد.' },
      winter:   { title: 'الشتاء الدافئ', text: 'معطف وحذاء دافئ وملابس شتوية لبرد مرتفعات سطيف. 3 500 دج للطفل.' },
      wildfire: { title: 'صندوق التضامن مع ضحايا الحرائق', text: 'دعم الأسر والأطفال المتضرّرين من حرائق الغابات.' },
      ramadan:  { title: 'قفّة رمضان', text: 'مواد غذائية للأسر المعوزة خلال شهر رمضان.' },
    },
    giveTo: 'تبرّع لهذا الصندوق',
    feesTitle: 'رسوم الدفع',
    feesText: 'الدفع بالبطاقة الذهبية أو CIB يتم في صفحة الدفع الآمنة لـ Chargily، ويقتطع مزوّد الدفع رسومًا صغيرة على كل عملية. لا تطّلع الجمعية على بيانات بطاقتك ولا تحتفظ بها.',
    inKindTitle: 'التبرّعات العينية',
    inKindText: 'اتصل بنا قبل إحضار أي أغراض. نقبل ما نحتاجه فعلًا في تلك الفترة، حتى يتمكّن المتطوّعون من تخزينه وتوزيعه كما يجب.',
    figuresTitle: 'عن الأرقام المعروضة',
    figuresIllustrative: 'أشرطة تقدّم الحملات تعرض حاليًا أرقامًا توضيحية، وستُستبدل بأرقام موثّقة حين تنشرها الجمعية.',
    figuresVerified: 'أرقام الحملات محدّثة من سجلّات الجمعية.',
    governanceTitle: 'من نحن قانونيًّا',
    governanceLead: 'جمعية إنصاف سطيف جمعية معتمدة وفق القانون الجزائري، يسيّرها مكتب تنفيذي منتخب ومسؤول أمام جمعيتها العامة.',
    facts: { founded: 'التأسيس', seat: 'المقر', registration: 'رقم الاعتماد', board: 'أعضاء المكتب التنفيذي' },
    foundedValue: 'جوان 2014',
    documentsTitle: 'الوثائق',
    documents: {
      statutes: 'القانون الأساسي للجمعية',
      registration: 'وصل التسجيل / الاعتماد',
      activityReport: 'التقرير الأدبي السنوي',
      financials: 'التقرير المالي السنوي',
      safeguarding: 'سياسة حماية الطفل',
    },
    pending: 'قريبًا',
    open: 'فتح',
    safeguardingTitle: 'حماية الطفل في عملنا',
    safeguardingText: 'نتّبع قواعد واضحة لحماية الأطفال في كل ما ننشره، ويمكن للأولياء أن يطلبوا منّا حذف أي صورة.',
    safeguardingLink: 'اقرأ التزاماتنا وحقوق الطفل',
    concern: 'قلق على طفل؟ اتصل بالرقم الأخضر 1111 (مجاني، 24/24).',
    channelsTitle: 'القنوات الرسمية وتنبيه من الاحتيال',
    channelsLead: 'قد يجمع أشخاص أموالًا باسم جمعيات معروفة. هذه قنواتنا الوحيدة:',
    channels: { site: 'هذا الموقع', facebook: 'صفحة فيسبوك الرسمية', phone: 'الهاتف', email: 'البريد الإلكتروني' },
    warningsTitle: 'لن نطلب منك أبدًا',
    warnings: [
      'الرقم السري لبطاقتك، أو كلمة المرور، أو رمز التأكيد المرسل عبر SMS.',
      'الدفع عبر رابط وصلك في رسالة. الدفع بالبطاقة يتم فقط في صفحة Chargily التي تُفتح من هذا الموقع.',
      'التحويل إلى حساب غير منشور في صفحة التبرّع على هذا الموقع.',
    ],
    verifyText: 'شخص يجمع التبرّعات باسم إنصاف ولست متأكدًا؟ اتصل بنا للتحقق قبل أن تدفع.',
    faqTitle: 'أسئلة المتبرّعين',
    faqs: [
      { q: 'هل يمكنني اختيار وجهة تبرّعي؟', a: 'نعم. في صفحة التبرّع تختار الصندوق، ويُسجَّل اختيارك مع العملية.' },
      { q: 'هل الدفع عبر الإنترنت آمن؟', a: 'تُدخل بيانات بطاقتك في صفحة الدفع الخاصة بـ Chargily، وليس في موقعنا. الجمعية لا ترى بيانات بطاقتك ولا تحتفظ بها.' },
      { q: 'لماذا الحد الأدنى 100 دج؟', a: 'يحمي الحد الأدنى نظام الدفع من برامج آلية تجرّب أرقام بطاقات مسروقة بمبالغ صغيرة جدًّا.' },
      { q: 'هل يمكنني التبرّع شهريًّا؟', a: 'التبرّع الشهري التلقائي غير متاح بعد مع البطاقات الجزائرية. يمكنك التبرّع يدويًّا كل شهر، ونعمل على تذكير يسهّل ذلك.' },
      { q: 'كيف أثبت تبرّعي؟', a: 'احتفظ بتأكيد الدفع. وإذا احتجت رسالة شكر أو إفادة من الجمعية، راسلنا.' },
      { q: 'هل الأرقام على الموقع حقيقية؟', a: 'الأرقام الموثّقة تظهر كما هي. وأي رقم لم يتم التحقق منه بعد يحمل عبارة «توضيحي» إلى أن تنشر الجمعية الأرقام الرسمية.' },
    ],
    candorTitle: 'حين يتعثّر شيء',
    candorText: 'المشاريع قد تتأخّر، والأرقام قد تتغيّر. التزامنا أن نكتب ذلك هنا بوضوح ومع التاريخ، بدل أن نتركك تكتشفه وحدك.',
    updated: 'آخر تحديث لهذه الصفحة',
    contactCta: 'اسألنا مباشرة',
  },

  fr: {
    promisesTitle: 'Quatre engagements envers chaque donateur',
    promises: [
      { id: 'choose', title: 'Vous choisissez la destination de votre don', text: 'Chaque don porte sa destination : rentrée scolaire, santé, hiver, fonds incendies, Ramadan, ou là où le besoin est le plus grand.' },
      { id: 'prove', title: 'Nous ne publions que ce que nous pouvons prouver', text: 'Tout chiffre non encore vérifié est signalé « illustratif » sur le site.' },
      { id: 'children', title: 'Les enfants d’abord', text: 'Ni nom complet, ni adresse, ni école d’un enfant dans ce que nous publions.' },
      { id: 'candid', title: 'Nous le disons quand quelque chose coince', text: 'Si un projet prend du retard ou qu’un chiffre change, nous l’écrivons ici, avec la date.' },
    ],
    fundsTitle: 'Où va votre dinar ?',
    fundsLead: 'Choisissez le fonds que vous voulez soutenir, ou laissez-nous l’affecter là où le besoin est le plus grand.',
    funds: {
      general:  { title: 'Là où le besoin est le plus grand', text: 'Affecté au programme le plus urgent du moment.' },
      school:   { title: 'Cartables scolaires', text: 'Cahiers, fournitures, cartable et tablier pour un enfant orphelin ou de famille modeste. 5 000 DA le cartable complet.' },
      health:   { title: 'Santé des enfants', text: 'Consultations, médicaments essentiels et suivi pendant l’année. 8 000 DA par enfant.' },
      winter:   { title: 'Hiver chaud', text: 'Manteau, chaussures chaudes et vêtements d’hiver contre le froid des hauts plateaux. 3 500 DA par enfant.' },
      wildfire: { title: 'Fonds de solidarité incendies', text: 'Soutien aux familles et aux enfants touchés par les feux de forêt.' },
      ramadan:  { title: 'Couffin du Ramadan', text: 'Denrées alimentaires pour les familles démunies pendant le Ramadan.' },
    },
    giveTo: 'Donner à ce fonds',
    feesTitle: 'Frais de paiement',
    feesText: 'Le paiement par carte Edahabia ou CIB se fait sur la page sécurisée de Chargily ; le prestataire de paiement prélève de petits frais sur chaque opération. L’association ne voit ni ne conserve les données de votre carte.',
    inKindTitle: 'Dons en nature',
    inKindText: 'Appelez-nous avant d’apporter des articles. Nous acceptons ce dont nous avons réellement besoin sur le moment, pour que les bénévoles puissent le stocker et le distribuer correctement.',
    figuresTitle: 'À propos des chiffres affichés',
    figuresIllustrative: 'Les barres de progression des campagnes affichent pour l’instant des chiffres illustratifs ; elles seront remplacées par des totaux vérifiés dès que l’association les publiera.',
    figuresVerified: 'Les chiffres des campagnes sont mis à jour à partir des registres de l’association.',
    governanceTitle: 'Qui nous sommes, juridiquement',
    governanceLead: 'Insaf Sétif est une association agréée de droit algérien, dirigée par un bureau exécutif élu et responsable devant son assemblée générale.',
    facts: { founded: 'Création', seat: 'Siège', registration: 'N° d’agrément', board: 'Membres du bureau exécutif' },
    foundedValue: 'Juin 2014',
    documentsTitle: 'Documents',
    documents: {
      statutes: 'Statuts de l’association',
      registration: 'Récépissé d’enregistrement / agrément',
      activityReport: 'Rapport moral annuel',
      financials: 'Rapport financier annuel',
      safeguarding: 'Politique de protection de l’enfant',
    },
    pending: 'Bientôt',
    open: 'Ouvrir',
    safeguardingTitle: 'La protection de l’enfant dans notre travail',
    safeguardingText: 'Nous suivons des règles claires pour protéger les enfants dans tout ce que nous publions, et un parent peut nous demander de retirer une photo.',
    safeguardingLink: 'Lire nos engagements et les droits de l’enfant',
    concern: 'Inquiet pour un enfant ? Appelez le numéro vert 1111 (gratuit, 24 h/24).',
    channelsTitle: 'Canaux officiels et alerte à la fraude',
    channelsLead: 'Des personnes collectent parfois de l’argent au nom d’associations connues. Voici nos seuls canaux :',
    channels: { site: 'Ce site', facebook: 'Page Facebook officielle', phone: 'Téléphone', email: 'E-mail' },
    warningsTitle: 'Nous ne vous demanderons jamais',
    warnings: [
      'Le code secret de votre carte, un mot de passe ou le code de confirmation reçu par SMS.',
      'De payer via un lien reçu par message. Le paiement par carte se fait uniquement sur la page Chargily ouverte depuis ce site.',
      'De virer vers un compte qui n’est pas publié sur la page Donner de ce site.',
    ],
    verifyText: 'Quelqu’un collecte au nom d’Insaf et vous avez un doute ? Appelez-nous pour vérifier avant de payer.',
    faqTitle: 'Questions des donateurs',
    faqs: [
      { q: 'Puis-je choisir la destination de mon don ?', a: 'Oui. Sur la page Donner, vous choisissez le fonds, et votre choix est enregistré avec l’opération.' },
      { q: 'Le paiement en ligne est-il sûr ?', a: 'Vous saisissez votre carte sur la page de paiement de Chargily, pas sur notre site. L’association ne voit ni ne conserve les données de votre carte.' },
      { q: 'Pourquoi un minimum de 100 DA ?', a: 'Ce minimum protège le système de paiement contre des robots qui testent des cartes volées avec de très petits montants.' },
      { q: 'Puis-je donner chaque mois ?', a: 'Le don mensuel automatique n’est pas encore possible avec les cartes algériennes. Vous pouvez donner chaque mois manuellement ; nous travaillons à un rappel pour vous faciliter la tâche.' },
      { q: 'Comment prouver mon don ?', a: 'Conservez la confirmation de paiement. Si vous avez besoin d’une lettre de remerciement ou d’une attestation de l’association, écrivez-nous.' },
      { q: 'Les chiffres du site sont-ils réels ?', a: 'Les chiffres vérifiés sont affichés tels quels. Tout chiffre pas encore vérifié porte la mention « illustratif » jusqu’à la publication des chiffres officiels par l’association.' },
    ],
    candorTitle: 'Quand quelque chose coince',
    candorText: 'Un projet peut prendre du retard, un chiffre peut changer. Nous nous engageons à l’écrire ici clairement et avec la date, plutôt que de vous laisser le découvrir seul.',
    updated: 'Dernière mise à jour de cette page',
    contactCta: 'Posez-nous la question',
  },

  en: {
    promisesTitle: 'Four promises to every donor',
    promises: [
      { id: 'choose', title: 'You choose where your gift goes', text: 'Every donation carries its destination: back to school, health, winter, the wildfire fund, Ramadan, or wherever the need is greatest.' },
      { id: 'prove', title: 'We only publish what we can prove', text: 'Any figure not yet verified is labelled “illustrative” on this site.' },
      { id: 'children', title: 'Children come first', text: 'No child’s full name, address or school in anything we publish.' },
      { id: 'candid', title: 'We say so when something goes wrong', text: 'If a project is delayed or a figure changes, we write it here, with the date.' },
    ],
    fundsTitle: 'Where does your dinar go?',
    fundsLead: 'Choose the fund you want to support, or let us direct it to where the need is greatest.',
    funds: {
      general:  { title: 'Where the need is greatest', text: 'Directed to the most urgent programme at the time.' },
      school:   { title: 'School kits', text: 'Notebooks, supplies, a school bag and smock for an orphan or a child from a low-income family. 5,000 DA for a full kit.' },
      health:   { title: 'Children’s healthcare', text: 'Check-ups, essential medicines and follow-up through the year. 8,000 DA per child.' },
      winter:   { title: 'Warm winter', text: 'A coat, warm shoes and winter clothes against the highland cold. 3,500 DA per child.' },
      wildfire: { title: 'Wildfire solidarity fund', text: 'Support for families and children affected by forest fires.' },
      ramadan:  { title: 'Ramadan food basket', text: 'Food for families in need during Ramadan.' },
    },
    giveTo: 'Give to this fund',
    feesTitle: 'Payment fees',
    feesText: 'Edahabia and CIB card payments happen on Chargily’s secure payment page, and the payment provider charges a small fee on each transaction. The association never sees or stores your card details.',
    inKindTitle: 'Donations in kind',
    inKindText: 'Please call us before bringing goods. We accept what is actually needed at the time, so volunteers can store and hand it out properly.',
    figuresTitle: 'About the figures on this site',
    figuresIllustrative: 'The campaign progress bars currently show illustrative figures. They will be replaced with verified totals as soon as the association publishes them.',
    figuresVerified: 'Campaign figures are updated from the association’s records.',
    governanceTitle: 'Who we are, legally',
    governanceLead: 'Insaf Sétif is a registered association under Algerian law, run by an elected executive board that answers to its general assembly.',
    facts: { founded: 'Founded', seat: 'Seat', registration: 'Registration no.', board: 'Executive board members' },
    foundedValue: 'June 2014',
    documentsTitle: 'Documents',
    documents: {
      statutes: 'Association statutes',
      registration: 'Registration certificate',
      activityReport: 'Annual activity report',
      financials: 'Annual financial report',
      safeguarding: 'Child safeguarding policy',
    },
    pending: 'Coming soon',
    open: 'Open',
    safeguardingTitle: 'Protecting children in our work',
    safeguardingText: 'We follow clear rules to protect children in everything we publish, and parents can ask us to remove a photo.',
    safeguardingLink: 'Read our commitments and children’s rights',
    concern: 'Worried about a child? Call the free 1111 line (24/7).',
    channelsTitle: 'Official channels and fraud warning',
    channelsLead: 'People sometimes collect money in the name of well-known associations. These are our only channels:',
    channels: { site: 'This website', facebook: 'Official Facebook page', phone: 'Phone', email: 'Email' },
    warningsTitle: 'We will never ask you for',
    warnings: [
      'Your card PIN, a password, or the confirmation code sent by SMS.',
      'A payment through a link sent to you in a message. Card payments only happen on the Chargily page opened from this site.',
      'A transfer to any account not published on this site’s donate page.',
    ],
    verifyText: 'Someone collecting in Insaf’s name and you’re not sure? Call us to check before you pay.',
    faqTitle: 'Donor questions',
    faqs: [
      { q: 'Can I choose where my donation goes?', a: 'Yes. On the donate page you pick the fund, and your choice is recorded with the payment.' },
      { q: 'Is paying online safe?', a: 'You enter your card on Chargily’s payment page, not on our site. The association never sees or stores your card details.' },
      { q: 'Why is there a 100 DA minimum?', a: 'The minimum protects the payment system from bots that test stolen card numbers with tiny amounts.' },
      { q: 'Can I give every month?', a: 'Automatic monthly giving isn’t available yet with Algerian cards. You can give manually each month, and we’re working on a reminder to make it easier.' },
      { q: 'How do I prove my donation?', a: 'Keep the payment confirmation. If you need a thank-you letter or a certificate from the association, write to us.' },
      { q: 'Are the figures on this site real?', a: 'Verified figures are shown as they are. Anything not yet verified is labelled “illustrative” until the association publishes official figures.' },
    ],
    candorTitle: 'When something goes wrong',
    candorText: 'Projects can be delayed and figures can change. We commit to writing it here, clearly and with the date, rather than leaving you to find out on your own.',
    updated: 'This page was last updated',
    contactCta: 'Ask us directly',
  },
};
